@startuml
actor traveler as traveler
participant application as application
participant user_management_service as user_management_service
participant database as database

traveler -> application: Visit Website
traveler -> application: Click on Login

traveler -> application: Enter Email and Password
traveler -> user_management_service: Request Authentication
user_management_service -> database: Query User Credentials
database --> user_management_service: User Credentials
user_management_service --> traveler: Authentication Result

traveler <- application: Login Success/Failure

@enduml
