@startuml
actor traveller as traveller
participant application as application
participant "OAuth Provider" as OAuthProvider

traveller -> application: Visit Website
traveller -> application: Click on Social Media Login

traveller -> application: Initiate OAuth Flow
application -> OAuthProvider: Redirect to OAuth Provider

traveller <- OAuthProvider: OAuth Redirect for Authentication
traveller -> OAuthProvider: Authorize Application

traveller <- OAuthProvider: OAuth Code

application -> OAuthProvider: Exchange OAuth Code
OAuthProvider --> application: Access Token

application -> OAuthProvider: Retrieve User Info
OAuthProvider --> application: User Info (Name, Email, etc.)

application -> application: Authenticate User

traveller <- application: Logged In

@enduml
