@startuml UseCaseDiagram
!define ICONURL https://plantuml.com/gicon/
!define TRAVELLER traveler
!define ADMINISTRATOR administrator
!define API_CLIENT api_client
!define APPLICATION application
!define UI_SERVICE ui_service
!define ADMIN_SERVICE admin_service
!define NOTIFICATION_SERVICE notification_service
!define AUDIT_LOGGING_SERVICE audit_logging_service
!define USER_MANAGEMENT_SERVICE user_management_service
!define TRIP_SERVICE trip_service
!define ANALYTICS_SERVICE analytics_service
!define TRAVEL_FEEDS travel_feeds
!define THIRD_PARTY_CONNECTORS thirdparty_connectors
!define EMAIL email
!define PNR pnr
!define BOOKING_ID booking_id


actor TRAVELLER as TRAVELLER #LightCyan

participant APPLICATION as APPLICATION
participant UI_SERVICE as UI_SERVICE
participant ANALYTICS_SERVICE as ANALYTICS_SERVICE




title "Travellers'  Trends Flow"


TRAVELLER -> UI_SERVICE: Requests travel trends
UI_SERVICE -> ANALYTICS_SERVICE: Analytics Data for the user
ANALYTICS_SERVICE -> database:
database -> ANALYTICS_SERVICE
ANALYTICS_SERVICE -> UI_SERVICE: travel trends
UI_SERVICE -> TRAVELLER




@enduml
